### ISSUE TITLE
ActiveRecord::StatementInvalid when creating record

### ISSUE THREAD

**Issue by Rhoxio** [samholst/friendly_slug#60]
When trying to save a model to Postgres 14.7, throws this error (from rspec test suite):

```
     Failure/Error: expect(post.save!).to be(true)
     
     ActiveRecord::StatementInvalid:
       PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type bigint: "NULL"
       LINE 1: ... FROM "posts" WHERE (slug = 'test-post' AND id != 'NULL') LI...
                                                                    ^
     # /Users/maze/.rvm/gems/ruby-3.1.2/gems/friendly_slug-0.1.8/lib/friendly_slug/active_record/base.rb:76:in `_slug_exists?'
     # /Users/maze/.rvm/gems/ruby-3.1.2/gems/friendly_slug-0.1.8/lib/friendly_slug/active_record/base.rb:51:in `_update_slug'
     # ./spec/posts/posts_spec.rb:7:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::InvalidTextRepresentation:
     #   ERROR:  invalid input syntax for type bigint: "NULL"
     #   LINE 1: ... FROM "posts" WHERE (slug = 'test-post' AND id != 'NULL') LI...
     #                                                                ^
     #   /Users/maze/.rvm/gems/ruby-3.1.2/gems/friendly_slug-0.1.8/lib/friendly_slug/active_record/base.rb:76:in `_slug_exists?'
```

Model is this:
```
class Post < ApplicationRecord
  attr_accessor :image_alt
  build_friendly_slug :title, use: :database

  has_many :images

  def delimit_title_with(symbol)
    return self.title.downcase.split(" ").join(symbol)
  end
end
```

The relevant migration looks like this: 
```
class AddSlugAndSubtitleToPosts < ActiveRecord::Migration[7.0]
  def change
    add_column :posts, :slug, :string, unique: true
    add_column :posts, :subtitle, :string
  end
end
```

schema.rb looks like this:
```
  create_table "posts", force: :cascade do |t|
    t.string "title"
    t.text "body"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "slug"
    t.string "subtitle"
  end
```

Test code looks like this and is quite simple:
```
require 'rails_helper'

describe Post do
  describe "create" do
    it "will create a post" do
      post = Post.new(title: "Test Post", body: "Text", subtitle: "Something")
      expect(post.save!).to be(true)
    end
  end
end
```

It seems to be an issue with the query in `_slug_exists?` where you are checking for NULL. 

It seems to work just fine with models that had a `title` and were then chain `save!`d before the integration of the gem.

**Comment by theprogramsam** [comment]
Thanks @Rhoxio, I will take a look into this :). Definitely related to the way Postgres queries construct vs MySQL. I believe just changing this line:

https://github.com/samholst/friendly_slug/blob/master/lib/friendly_slug/active_record/base.rb#L97

to:

```ruby
self.class.where("slug = ? AND id != ?", current_slug, self.id.nil? ? nil : self.id).any? 
```

may do the trick, but I'll have to test that when I have some time.
